Found it!

diff --git a/.github/actions/install-conjure/action.yml b/.github/actions/install-conjure/action.yml
--- a/.github/actions/install-conjure/action.yml
+++ b/.github/actions/install-conjure/action.yml
@@ -26,16 +26,16 @@ runs:
 
             echo "Adding conjure to path."
             # this prepends to path (so imagemagick doesnt interfere!), and does not take effect until the next step runs.
-            echo "${HOME}/conjure/conjure-v${{ env.conjure_version }}-${{ env.release_suffix }}-with-solvers/" >> ${GITHUB_PATH}
+            echo "${HOME}/conjure/conjure-v${{ inputs.version }}-${{ inputs.release_suffix }}-with-solvers/" >> ${GITHUB_PATH}
           fi
       shell: bash
 
-    #- name: Check that conjure is installed correctly
-    #  run: | 
-    #      if [ "$(conjure --version | head -n2 | tail -n1)" != "Release version ${{ inputs.version }}" ]; then
-    #        echo "Correct conjure not found in path."
-    #        conjure --version
-    #        exit 1
-    #      fi
-    #  shell: bash
+    - name: Check that conjure is installed correctly
+      run: | 
+          if [ "$(conjure --version | head -n2 | tail -n1)" != "Release version ${{ inputs.version }}" ]; then
+            echo "Correct conjure not found in path."
+            conjure --version
+            exit 1
+          fi
+      shell: bash
 
