ci: temporarily use Conjure nightly

diff --git a/.github/actions/install-conjure/action.yml b/.github/actions/install-conjure/action.yml
--- a/.github/actions/install-conjure/action.yml
+++ b/.github/actions/install-conjure/action.yml
@@ -4,7 +4,7 @@ inputs:
   version:
     description: "The version of conjure to install."
     required: false
-    default: "v2.6.1"
+    default: "nightly"
   os_arch:
     description: 'The OS / Architecture to use. Supported values are ["linux", "macos", "macos-intel"]'
     required: true
@@ -19,7 +19,14 @@ runs:
     shell: bash
 
   - run: |
-      if [[ $(conjure --version | head -n2 | tail -n1) != "Conjure ${{ inputs.version }}"* ]]; then
+      needs_install=false
+      if [[ "${{ inputs.version }}" == "nightly" ]]; then
+        needs_install=true
+      elif [[ $(conjure --version | head -n2 | tail -n1) != "Conjure ${{ inputs.version }}"* ]]; then
+        needs_install=true
+      fi
+
+      if [[ "${needs_install}" == "true" ]]; then
         mkdir -p "${HOME}/conjure"
         cd "${HOME}/conjure"
 
@@ -34,9 +41,13 @@ runs:
 
   - name: Check that conjure is installed correctly
     run: |
-      if [[ $(conjure --version | head -n2 | tail -n1) != "Conjure ${{ inputs.version }}"* ]]; then
+      if [[ "${{ inputs.version }}" == "nightly" ]] && ! command -v conjure >/dev/null; then
+        echo "Conjure not found in path."
+        exit 1
+      elif [[ "${{ inputs.version }}" != "nightly" && $(conjure --version | head -n2 | tail -n1) != "Conjure ${{ inputs.version }}"* ]]; then
         echo "Correct conjure not found in path."
         conjure --version
         exit 1
       fi
+      conjure --version
     shell: bash
